# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - LR4_R560_joint1
      - LR4_R560_joint2
      - LR4_R560_joint3
      - LR4_R560_joint4
      - LR4_R560_joint5
      - LR4_R560_joint6
    action_ns: follow_joint_trajectory
    default: true